version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.7.4
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.4
            bundle install
            bundle exec rake
